config: /config
data: /data
   GTSRB: /data/GTSRB
   Test: /data/GTSRB/Final_Test/Images
   Training: /data/GTSRB/Final_Training/Images
reports: /reports
scripts: /scripts
src: /src
   data: /src/data
   models: /src/models
   training: /src/training
   utils: /src/utils
tests: /tests